from enum import Enum
from typing import Optional

class PyIQAMetric(Enum):
    AHIQ = ('ahiq', 'FR')
    CKDN = ('ckdn', 'FR')
    LPIPS = ('lpips', 'FR')
    LPIPS_VGG = ('lpips', 'FR')
    LPIPS_PLUS = ('lpips', 'FR')
    LPIPS_VGG_PLUS = ('lpips', 'FR')
    STLPIPS = ('stlpips', 'FR')
    STLPIPS_VGG = ('stlpips', 'FR')
    DISTS = ('dists', 'FR')
    SSIM = ('ssim', 'FR')
    SSIMC = ('ssim', 'FR')
    PSNR = ('psnr', 'FR')
    PSNRY = ('psnr', 'FR')
    FSIM = ('fsim', 'FR')
    MS_SSIM = ('ms_ssim', 'FR')
    VIF = ('vif', 'FR')
    GMSD = ('gmsd', 'FR')
    NLPD = ('nlpd', 'FR')
    VSI = ('vsi', 'FR')
    CW_SSIM = ('cw_ssim', 'FR')
    MAD = ('mad', 'FR')
    PIQE = ('piqe', 'NR')
    NIQE = ('niqe', 'NR')
    NIQE_MATLAB = ('niqe', 'NR')
    ILNIQE = ('ilniqe', 'NR')
    BRISQUE = ('brisque', 'NR')
    BRISQUE_MATLAB = ('brisque', 'NR')
    NRQM = ('nrqm', 'NR')
    PI = ('pi', 'NR')
    CNNIQA = ('cnniqa', 'NR')
    MUSIQ = ('musiq', 'NR')
    MUSIQ_AVA = ('musiq', 'NR')
    MUSIQ_PAQ2PIQ = ('musiq', 'NR')
    MUSIQ_SPAQ = ('musiq', 'NR')
    NIMA = ('nima', 'NR')
    NIMA_KONIQ = ('nima', 'NR')
    NIMA_SPAQ = ('nima', 'NR')
    NIMA_VGG16_AVA = ('nima', 'NR')
    PIEAPP = ('pieapp', 'FR')
    PAQ2PIQ = ('paq2piq', 'NR')
    DBCNN = ('dbcnn', 'NR')
    FID = ('fid', 'NR')
    MANIQA = ('maniqa', 'NR')
    MANIQA_PIPAL = ('maniqa', 'NR')
    MANIQA_KADID = ('maniqa', 'NR')
    CLIPIQA = ('clipiqa', 'NR')
    CLIPIQA_PLUS = ('clipiqa', 'NR')
    CLIPIQA_PLUS_VITL14_512 = ('clipiqa', 'NR')
    CLIPIQA_PLUS_RN50_512 = ('clipiqa', 'NR')
    TRES = ('tres', 'NR')
    TRES_FLIVE = ('tres', 'NR')
    HYPERIQA = ('hypernet', 'NR')
    URANKER = ('uranker', 'NR')
    CLIPSCORE = ('clipscore', 'NR')
    ENTROPY = ('entropy', 'NR')
    TOPIQ_NR = ('cfanet', 'NR')
    TOPIQ_NR_FLIVE = ('cfanet', 'NR')
    TOPIQ_NR_SPAQ = ('cfanet', 'NR')
    TOPIQ_NR_FACE = ('cfanet', 'NR')
    TOPIQ_FR = ('cfanet', 'FR')
    TOPIQ_FR_PIPAL = ('cfanet', 'FR')
    TOPIQ_IAA = ('cfanet', 'NR')
    TOPIQ_IAA_RES50 = ('cfanet', 'NR')
    LAION_AES = ('laionaes', 'NR')
    LIQE = ('liqe', 'NR')
    LIQE_MIX = ('liqe', 'NR')
    WADIQAM_FR = ('wadiqam', 'FR')
    WADIQAM_NR = ('wadiqam', 'NR')
    QALIGN = ('qalign', 'NR')
    QALIGN_8BIT = ('qalign', 'NR')
    QALIGN_4BIT = ('qalign', 'NR')
    UNIQUE = ('unique', 'NR')
    INCEPTION_SCORE = ('inceptionscore', 'NR')
    ARNIQA = ('arniqa', 'NR')
    ARNIQA_LIVE = ('arniqa', 'NR')
    ARNIQA_CSIQ = ('arniqa', 'NR')
    ARNIQA_TID = ('arniqa', 'NR')
    ARNIQA_KADID = ('arniqa', 'NR')
    ARNIQA_CLIVE = ('arniqa', 'NR')
    ARNIQA_FLIVE = ('arniqa', 'NR')
    ARNIQA_SPAQ = ('arniqa', 'NR')
    MSSWD = ('ms_swd_learned', 'FR')

    def __init__(self, metric_name: str, metric_type: str):
        self.metric_name = metric_name
        self.metric_type = metric_type

    @classmethod
    def from_string(cls, metric_name: str) -> Optional['PyIQAMetric']:
        for metric in cls:
            if metric.metric_name == metric_name.lower():
                return metric
        return None